site_name: Project Documentation
nav:
  - Home: index.md
  - About: about.md
  - Help: help.md
theme: 
  name: mkdocs
  logo: img/favicon.ico        # small logo in header
  favicon: img/favicon.ico
#extra:
#  favicon: img/favicon.ico
