site_name: Project Documentation
nav:
  - Home: index.md
  - About: about.md
  - Help: help.md
theme: 
  name: mkdocs
  logo: images/header.png        # small logo in header
  favicon: images/favicon.ico
#extra:
#  favicon: img/favicon.ico
